/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dbdad5",
        "surface-container": "#f0eee9",
        "tertiary-fixed-dim": "#d0c4bb",
        "surface-container-low": "#f5f3ee",
        "on-tertiary-fixed": "#201a15",
        "primary-fixed": "#e9e1dd",
        "on-surface-variant": "#4d4540",
        "on-secondary": "#ffffff",
        "accent-terracotta": "#C85A32",
        "outline": "#7e7570",
        "secondary-fixed": "#ffdbcf",
        "ink-primary": "#1A1715",
        "primary-container": "#1e1b19",
        "secondary-fixed-dim": "#ffb59c",
        "primary-fixed-dim": "#ccc5c1",
        "on-surface": "#1b1c19",
        "on-secondary-fixed-variant": "#822801",
        "surface-container-high": "#eae8e3",
        "on-tertiary-fixed-variant": "#4d453f",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#4a4643",
        "surface-cream": "#EFECE4",
        "primary": "#000000",
        "inverse-primary": "#ccc5c1",
        "tertiary": "#000000",
        "on-primary-fixed": "#1e1b19",
        "ink-secondary": "#57524D",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "canvas-paper": "#F7F5F0",
        "background": "#fbf9f4",
        "secondary": "#a23e18",
        "surface-bright": "#fbf9f4",
        "on-secondary-container": "#6f2000",
        "on-primary-container": "#888380",
        "error": "#ba1a1a",
        "on-background": "#1b1c19",
        "surface-variant": "#e4e2dd",
        "border-hairline": "rgba(26, 23, 21, 0.12)",
        "surface": "#fbf9f4",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f2f1ec",
        "inverse-surface": "#30312e",
        "surface-tint": "#E5E1D6",
        "secondary-container": "#fe8357",
        "outline-variant": "#d0c4be",
        "surface-container-highest": "#e4e2dd",
        "tertiary-fixed": "#ede0d7",
        "status-alert": "#A63224",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#8c827a",
        "on-secondary-fixed": "#390c00",
        "ink-muted": "#8C827A",
        "tertiary-container": "#201a15",
        "status-warning": "#B85324",
      },
      borderRadius: {
        none: "0px",
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1.25rem",
        "margin-tablet": "2rem",
        "space-xl": "4.5rem",
        "gutter-mobile": "1rem",
        "gutter": "2.5rem",
        "space-sm": "0.75rem",
        "space-2xl": "7rem",
        "space-lg": "2.5rem",
        "space-xs": "0.5rem",
        "margin": "4rem",
        "space-md": "1.5rem",
      },
      fontFamily: {
        "numeric-hero-mobile": ["Epilogue", "sans-serif"],
        "headline-xl": ["Epilogue", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "body-xl": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "display-hero-mobile": ["Epilogue", "sans-serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "numeric-hero": ["Epilogue", "sans-serif"],
        "headline-xl-mobile": ["Epilogue", "sans-serif"],
        "display-hero": ["Epilogue", "sans-serif"],
        "headline-lg": ["Epilogue", "sans-serif"],
        sans: ["Manrope", "sans-serif"],
        serif: ["Epilogue", "serif"],
      },
      fontSize: {
        "numeric-hero-mobile": ["48px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "500" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-xl": ["20px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "numeric-hero": ["72px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "500" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
