"""initial_schema

Revision ID: c014e8a84b43
Revises: 
Create Date: 2026-09-20 01:06:58.792401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c014e8a84b43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_operation_type'), 'ai_analyses', ['operation_type'], unique=False)
    op.create_index(op.f('ix_ai_analyses_user_id'), 'ai_analyses', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('total_planned_minutes', sa.Integer(), nullable=False),
    sa.Column('total_completed_minutes', sa.Integer(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_plan_date'), 'plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('time_availability',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('capacity_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_availability_id'), 'time_availability', ['id'], unique=False)
    op.create_index(op.f('ix_time_availability_user_id'), 'time_availability', ['user_id'], unique=False)
    op.create_table('user_interests',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('target_weekly_hours', sa.Float(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('color_hex', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interests_id'), 'user_interests', ['id'], unique=False)
    op.create_index(op.f('ix_user_interests_user_id'), 'user_interests', ['user_id'], unique=False)
    op.create_table('user_pace_factors',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('pace_factor', sa.Float(), nullable=False),
    sa.Column('total_estimated_hours', sa.Float(), nullable=False),
    sa.Column('total_actual_hours', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_pace_factors_category'), 'user_pace_factors', ['category'], unique=False)
    op.create_index(op.f('ix_user_pace_factors_id'), 'user_pace_factors', ['id'], unique=False)
    op.create_index(op.f('ix_user_pace_factors_user_id'), 'user_pace_factors', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('daily_focus_capacity_hours', sa.Float(), nullable=False),
    sa.Column('buffer_percentage', sa.Float(), nullable=False),
    sa.Column('preferred_work_chunk_minutes', sa.Integer(), nullable=False),
    sa.Column('min_break_minutes', sa.Integer(), nullable=False),
    sa.Column('remind_risk_escalation', sa.Boolean(), nullable=False),
    sa.Column('remind_7_days', sa.Boolean(), nullable=False),
    sa.Column('remind_3_days', sa.Boolean(), nullable=False),
    sa.Column('remind_1_day', sa.Boolean(), nullable=False),
    sa.Column('morning_plan_briefing', sa.Boolean(), nullable=False),
    sa.Column('briefing_time', sa.String(length=8), nullable=False),
    sa.Column('ai_assistance_enabled', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('work_items',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=False),
    sa.Column('deadline_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_hard_deadline', sa.Boolean(), nullable=False),
    sa.Column('deadline_timezone', sa.String(length=64), nullable=False),
    sa.Column('is_deadline_inferred', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_estimated_hours', sa.Float(), nullable=False),
    sa.Column('remaining_estimated_hours', sa.Float(), nullable=False),
    sa.Column('total_actual_hours', sa.Float(), nullable=False),
    sa.Column('completion_pct', sa.Integer(), nullable=False),
    sa.Column('risk_state', sa.String(length=32), nullable=False),
    sa.Column('risk_ratio', sa.Float(), nullable=False),
    sa.Column('dynamic_priority', sa.Float(), nullable=False),
    sa.Column('priority_explanation', sa.Text(), nullable=True),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_items_category'), 'work_items', ['category'], unique=False)
    op.create_index(op.f('ix_work_items_deadline_utc'), 'work_items', ['deadline_utc'], unique=False)
    op.create_index(op.f('ix_work_items_dynamic_priority'), 'work_items', ['dynamic_priority'], unique=False)
    op.create_index(op.f('ix_work_items_id'), 'work_items', ['id'], unique=False)
    op.create_index(op.f('ix_work_items_risk_state'), 'work_items', ['risk_state'], unique=False)
    op.create_index(op.f('ix_work_items_status'), 'work_items', ['status'], unique=False)
    op.create_index(op.f('ix_work_items_user_id'), 'work_items', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('urgency_level', sa.String(length=32), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_work_item_id'), 'notifications', ['work_item_id'], unique=False)
    op.create_table('schedule_blocks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('interest_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('block_type', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_blackout', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['user_interests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_blocks_end_time'), 'schedule_blocks', ['end_time'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_id'), 'schedule_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_interest_id'), 'schedule_blocks', ['interest_id'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_start_time'), 'schedule_blocks', ['start_time'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_user_id'), 'schedule_blocks', ['user_id'], unique=False)
    op.create_table('work_units',
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('actual_hours', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_user_verified', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_units_id'), 'work_units', ['id'], unique=False)
    op.create_index(op.f('ix_work_units_is_completed'), 'work_units', ['is_completed'], unique=False)
    op.create_index(op.f('ix_work_units_sequence_order'), 'work_units', ['sequence_order'], unique=False)
    op.create_index(op.f('ix_work_units_user_id'), 'work_units', ['user_id'], unique=False)
    op.create_index(op.f('ix_work_units_work_item_id'), 'work_units', ['work_item_id'], unique=False)
    op.create_table('active_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('work_unit_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_sessions_id'), 'active_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_active_sessions_user_id'), 'active_sessions', ['user_id'], unique=True)
    op.create_index(op.f('ix_active_sessions_work_item_id'), 'active_sessions', ['work_item_id'], unique=False)
    op.create_index(op.f('ix_active_sessions_work_unit_id'), 'active_sessions', ['work_unit_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('work_unit_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_items_id'), 'plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_plan_items_plan_id'), 'plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_items_sequence_order'), 'plan_items', ['sequence_order'], unique=False)
    op.create_index(op.f('ix_plan_items_work_item_id'), 'plan_items', ['work_item_id'], unique=False)
    op.create_index(op.f('ix_plan_items_work_unit_id'), 'plan_items', ['work_unit_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('work_unit_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_end_time'), 'time_entries', ['end_time'], unique=False)
    op.create_index(op.f('ix_time_entries_id'), 'time_entries', ['id'], unique=False)
    op.create_index(op.f('ix_time_entries_start_time'), 'time_entries', ['start_time'], unique=False)
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_time_entries_work_item_id'), 'time_entries', ['work_item_id'], unique=False)
    op.create_index(op.f('ix_time_entries_work_unit_id'), 'time_entries', ['work_unit_id'], unique=False)
    op.create_table('work_estimates',
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('work_unit_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('estimate_type', sa.String(length=32), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_estimates_id'), 'work_estimates', ['id'], unique=False)
    op.create_index(op.f('ix_work_estimates_user_id'), 'work_estimates', ['user_id'], unique=False)
    op.create_index(op.f('ix_work_estimates_work_item_id'), 'work_estimates', ['work_item_id'], unique=False)
    op.create_index(op.f('ix_work_estimates_work_unit_id'), 'work_estimates', ['work_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_estimates_work_unit_id'), table_name='work_estimates')
    op.drop_index(op.f('ix_work_estimates_work_item_id'), table_name='work_estimates')
    op.drop_index(op.f('ix_work_estimates_user_id'), table_name='work_estimates')
    op.drop_index(op.f('ix_work_estimates_id'), table_name='work_estimates')
    op.drop_table('work_estimates')
    op.drop_index(op.f('ix_time_entries_work_unit_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_work_item_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_start_time'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_end_time'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_plan_items_work_unit_id'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_work_item_id'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_sequence_order'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_plan_id'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_active_sessions_work_unit_id'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_work_item_id'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_user_id'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_id'), table_name='active_sessions')
    op.drop_table('active_sessions')
    op.drop_index(op.f('ix_work_units_work_item_id'), table_name='work_units')
    op.drop_index(op.f('ix_work_units_user_id'), table_name='work_units')
    op.drop_index(op.f('ix_work_units_sequence_order'), table_name='work_units')
    op.drop_index(op.f('ix_work_units_is_completed'), table_name='work_units')
    op.drop_index(op.f('ix_work_units_id'), table_name='work_units')
    op.drop_table('work_units')
    op.drop_index(op.f('ix_schedule_blocks_user_id'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_start_time'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_interest_id'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_id'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_end_time'), table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    op.drop_index(op.f('ix_notifications_work_item_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_work_items_user_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_status'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_risk_state'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_dynamic_priority'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_deadline_utc'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_category'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_pace_factors_user_id'), table_name='user_pace_factors')
    op.drop_index(op.f('ix_user_pace_factors_id'), table_name='user_pace_factors')
    op.drop_index(op.f('ix_user_pace_factors_category'), table_name='user_pace_factors')
    op.drop_table('user_pace_factors')
    op.drop_index(op.f('ix_user_interests_user_id'), table_name='user_interests')
    op.drop_index(op.f('ix_user_interests_id'), table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_time_availability_user_id'), table_name='time_availability')
    op.drop_index(op.f('ix_time_availability_id'), table_name='time_availability')
    op.drop_table('time_availability')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_plan_date'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_ai_analyses_user_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_operation_type'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
